name = "lesson2"
compatibility_date = "2025-01-20"

# 静的サイト（Pages）用設定
[assets]
directory = "."
include = ["*.html", "*.js", "*.css", "_headers", "assets/**/*", "src/api/**/*"]
exclude = ["node_modules/**/*", ".git/**/*", "src/db/**/*", "migrations/**/*", "docs/**/*", "*.md", "package*.json", "tsconfig.json"]

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "shelf-designer-db"
database_id = ""  # wrangler d1 create 実行後に設定

# Environment Variables
[vars]
API_BASE_URL = "https://lesson2.pages.dev"
NODE_VERSION = "18"

# Build settings
[build]
command = ""