name = "lesson3"
compatibility_date = "2025-01-20"

# 静的サイト（Pages）用設定
[assets]
directory = "public"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "shelf-designer-db"
database_id = ""  # wrangler d1 create 実行後に設定

# Environment Variables
[vars]
API_BASE_URL = "https://lesson3.pages.dev"
NODE_VERSION = "18"

# Build settings
[build]
command = ""