name = "lesson2"
compatibility_date = "2025-01-20"

# 静的サイト（Pages）用設定
pages_build_output_dir = "public"

# Pages Functions設定
[env.production]
compatibility_flags = ["nodejs_compat"]

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "shelf-designer-db"
database_id = "40bfceaa-1a06-4d58-b1a2-957f2da6d852"

# Environment Variables
[vars]
API_BASE_URL = "https://lesson2-apo.pages.dev"
NODE_VERSION = "18"

